server:
  port: 8082

spring:
  application:
    name: chessonline

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:${POSTGRES_PORT:5433}/chessonline}
    username: ${POSTGRES_USER:chess}
    password: ${POSTGRES_PASSWORD:chesspass}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings

security:
  jwt:
    secret: ${JWT_SECRET:dev-secret-change-me-please-32-bytes-minimum}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}

puzzle:
  csv:
    path: ${PUZZLE_CSV_PATH:/home/nikita/Desktop/play code/online-chess/puzzles/lichess_db_puzzle.csv.zst}
